spring:
  application:
    name: consul-es-web-quartz
  # 数据源配置
  datasource:
    password: root
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springboot?serverTimezone=UTC
  #    ## 人大金仓数据源
  #    url: jdbc:kingbase8://127.0.0.1:54321/TEST
  #    username: SYSTEM #e789e20acb9d1cad # system
  #    password: 123456 #9f1dea4fdfa1a8f4 # 123456
  #    driver-class-name: com.kingbase8.Driver
  # mvc视图模板配置
  thymeleaf:
    cache: true
    suffix: .html
    prefix: classpath:templates/
    mode: HTML
    enabled: true
  boot:
    # admin应用监控client端配置
    admin:
      client:
        instance:
          prefer-ip: true
        url: http://127.0.0.1:8001
        username: admin
        password: admin
  #  # es springboot配置 ElasticsearchRestClientAutoConfiguration
  #  elasticsearch:
  #    rest:
  #      connection-timeout: 1s
  #      uris: http://localhost:9200
  #      username:
  #      password:
  #      read-timeout: 30s
  data:
    # es配置：ReactiveElasticsearchRestClientAutoConfiguration
    elasticsearch:
      repositories:
        enabled: true
      client:
        reactive:
          connection-timeout: 1s
          endpoints: localhost:9200
          username:
          password:
    # mongo配置：MongoReactiveAutoConfiguration or MongoAutoConfiguration
    mongodb:
      #      uri: mongodb://localhost/test
      port: 27017
      host: localhost
      database: springboot
      username: admin
      password: admin
  # redis配置： RedisAutoConfiguration
  redis:
    database: 9
    host: 127.0.0.1
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: -1
        min-idle: 0
    port: 6379
    timeout: 6000
    password:
  # jpa配置：显示sql，自动创建表
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  #    properties:
  #      hibernate:
  #        dialect: org.hibernate.dialect.Kingbase8Dialect
  # quartz 定时任务配置：QuartzAutoConfiguration
  quartz:
    auto-startup: true
    # quartz.properties 属性配置
    properties:
      org:
        quartz:
          ## 调度器
          scheduler:
            instanceName: clusteredScheduler
            instanceId: AUTO
          ## 任务数据存储
          jobStore:
            class: org.quartz.impl.jdbcjobstore.JobStoreTX
            driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate
            ## 表前缀
            tablePrefix: QRTZ_
            ## 多节点定时任务？
            isClustered: true
            clusterCheckinInterval: 10000
            useProperties: false
          ## 任务线程池
          threadPool:
            class: org.quartz.simpl.SimpleThreadPool
            threadCount: 10
            threadPriority: 5
            threadsInheritContextClassLoaderOfInitializingThread: true
    # 任务数据持久化方式：默认为内存memory，
    job-store-type: jdbc
    scheduler-name: quartzScheduler
  # 轻量级目录服务
  ldap:
    #    # 嵌入式ldap配置:EmbeddedLdapAutoConfiguration
    #    embedded:
    #      ldif: classpath:ldap-server.ldif
    #      base-dn: dc=didispace,dc=com
    urls: ldap://localhost:389
    base: dc=maxcrc,dc=com
    username: maxcrc
    password: secret
server:
  port: 8080

# mybatis配置
mybatis:
  type-aliases-package: com.demo.springboot.consulesweb.entity
  mapper-locations: classpath:mappers/*Mapper.xml
# 日志配置：mybatis显示sql
logging:
  level:
    com:
      demo:
        springboot:
          consulesweb:
            dao: debug

# 自定义配置 es
#aliyun:
#  es:
#    url: localhost:9200
#    username:
#    password:

# hbase 配置
hbase:
  config:
    hbase.zookeeper.quorum: 192.168.200.71,192.168.200.73
    hbase.zookeeper.property.clientPort: 2181
zookeeper:
  znode:
    parent: /hbase