# 日志配置
logging:
  level:
    com:
      demo:
        springboot:
          web:
            mapper: debug
# actuator 监管端点配置
management:
  endpoint:
    health:
      show-details: ALWAYS
  endpoints:
    web:
      exposure:
        include: '*'
# mybatis配置
mybatis:
  mapper-locations: classpath:mybatis.mapper/*.xml
  type-aliases-package: com.demo.springboot.web.entity
# 端口
server:
  port: 8080
spring:
  devtools:
    restart:
      ## 开启热部署，原理：另一个ClassLoader加载会更改的类，称为restart ClassLoader
      enabled: true
  application:
    name: web
  boot:
    admin:
      client:
        password: admin
        username: admin
        # 监管server端url
        url: http://127.0.0.1:8001
  # spring boot 应用级缓存
  cache:
    cache-names: accounts,orders,users
    caffeine:
      spec: initialCapacity=10,maximumSize=500,expireAfterAccess=600s
    type: caffeine
  # spring boot mongo配置
  data:
    mongodb:
      uri: mongodb://localhost:27017/mytestdb
  # mysql数据源
  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    name: springboot
#    password: root
#    url: jdbc:mysql://localhost:3306/springboot?serverTimezone=UTC
#    username: root
    ## 人大金仓数据源
    url: jdbc:kingbase8://47.96.100.96:54321/TEST
    username: SYSTEM #e789e20acb9d1cad # 注意大小写
    password: 123456 #9f1dea4fdfa1a8f4 # 123456
    driver-class-name: com.kingbase8.Driver
  # spring boot 邮件的配置
  mail:
    host: smtp.163.com
    password: BFLBDFEZDSAFERZO
    port: 465
    properties:
      from: huifeidezhu_12138@163.com
      mail:
        smtp:
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory
    username: huifeidezhu_12138@163.com
  # spring boot webmvc配置
  mvc:
    view:
      prefix: classpath:view/
      suffix: .html
  # redis配置
  redis:
    database: 4
    host: 127.0.0.1
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: -1
        min-idle: 0
    port: 6379
    timeout: 6000ms
    redisson:
      file: classpath:redisson.yml
  # thymleaf 模板引擎配置
  thymeleaf:
    prefix: classpath:view/
    suffix: .html
# 阿里云oss 自定义配置
aliyun:
  accessKeyId: #自己的accessKey
  accessKeySecret: #自己的accessSecret
  oss:
    endpoint: https://oss-cn-beijing.aliyuncs.com
    bucketName: bucket-test12138
    urlPrefix: https://bucket-test12138.oss-cn-beijing.aliyuncs.com/
# 策略开关-注入不同的bean实现
stragety:
  type: vip1