# 待确定。。。。。
# 日志配置
logging:
  level:
    com:
      demo:
        springboot:
          web:
            mapper: error
# actuator 监管端点配置
management:
  endpoint:
    health:
      show-details: ALWAYS
  endpoints:
    web:
      exposure:
        include: '*'
# mybatis配置
mybatis:
  mapper-locations: classpath:mybatis.mapper/*.xml
  type-aliases-package: com.demo.springboot.web.entity
# 端口
server:
  port: 8080
spring:
  application:
    name: web
#  boot:
#    admin:
#      client:
#        password: admin
#        username: admin
#        # 监管server端url
#        url: http://127.0.0.1:8001
  # spring boot 应用级缓存
  cache:
    cache-names: accounts,orders,users
    caffeine:
      spec: initialCapacity=10,maximumSize=500,expireAfterAccess=600s
    type: caffeine
  # spring boot mongo配置
#  data:
#    mongodb:
#      uri: mongodb://localhost:27017/mytestdb
  # mysql数据源
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    name: springboot
    password: root
    url: jdbc:mysql://localhost:3306/springboot?serverTimezone=UTC
    username: root
  # spring boot 邮件的配置
  mail:
    host: smtp.163.com
    password: BFLBDFEZDSAFERZO
    port: 465
    properties:
      from: huifeidezhu_12138@163.com
      mail:
        smtp:
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory
    username: huifeidezhu_12138@163.com
  # spring boot webmvc配置
  mvc:
    view:
      prefix: classpath:view/
      suffix: .html
  # redis配置
  redis:
    database: 4
    host: 127.0.0.1
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: -1
        min-idle: 0
    port: 6379
    timeout: 6000ms
    redisson:
      file: classpath:redisson.yml
  # thymleaf 模板引擎配置
  thymeleaf:
    prefix: classpath:view/
    suffix: .html
# 阿里云oss 自定义配置
aliyun:
  accessKeyId: # 使用自己的Accesskey
  accessKeySecret: # 秘钥
  oss:
    endpoint: https://oss-cn-beijing.aliyuncs.com
    bucketName: bucket-test12138
    urlPrefix: https://bucket-test12138.oss-cn-beijing.aliyuncs.com/