spring:
  application:
    # 应用名称
    name: dbconnector
  # 主数据源配置
  datasource:
    password: root
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    name: sso-db
    url: jdbc:mysql://localhost:3306/sso-db?serverTimezone=UTC
# 端口
server:
  port: 8888
