server:
  port: 9827

spring:
  application:
    name: redission-with-springboot
  redis:
    cluster:
      nodes: 127.0.0.1:6381,127.0.0.1:6382,127.0.0.1:6383,127.0.0.1:6384,127.0.0.1:6385,127.0.0.1:6386
      max-redirects: 3
    password:
    lettuce:
      pool:
        max-active: 32
        max-idle: 16
        min-idle: 8