server:
  port: 9090
spring:
  application:
    name: es7-with-resthighlevelclient
## es7 配置
elasticsearch:
  ## 账户认证配置
  account:
    username:
    password:
  ##协议
  schema: http
  ## 集群名称
  cluster-name: my-es7-cluster
  ## 节点数组(host:port格式)
  cluster-nodes:
    - localhost:9200
    - localhost:9201
    - localhost:9202
  ## 连接超时时间
  connect-timeout: 1000
  ## socket 超时时间
  socket-timeout: 30000
  ## 连接请求超时时间
  connection-request-timeout: 500
  ## 每个路由最大连接数
  max-connect-per-route: 10
  ## 总最大连接数
  max-connect-total: 30
  ## 索引index配置信息
  index:
    number-of-replicas: 0
    number-of-shards: 3
