server:
  port: 8080
  # 内嵌tomcat配置
  tomcat:
    # 最大连接数：能处理的最大并发量
    max-connections: 8192
    threads:
      # 最大线程数：采用nio，多路复用技术处理socket连接，200个线程处理8192个并发请求
      max: 200
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    name: springboot
    password: root
    url: jdbc:mysql://localhost:3306/springboot?serverTimezone=UTC
    username: root
# mybatis配置
mybatis:
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: com.demo.springboot.mybatiswithspringboot.entity