spring:
  application:
    name: spring-cloud-seuth
  datasource:
    url: jdbc:mysql://localhost/springboot
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  sleuth:
    enabled: true
    sampler:
      #即100%的概率将链路的数据上传给Zipkin Server
      rate: 1
      probability: 1.0
  zipkin:
    enabled: true
    rabbitmq:
      addresses: localhost:5672
      queue: zipkin
    # zipkin-service的 访问地址
    base-url: http://localhost:9411
